
var countries = {
	AFG:	"Afganistán",
	AGO:	"Angola",
	ALB:	"Albania",
	AND:	"Andorra ",
	ARE:	"Emiratos Árabes Unidos",
	ARG:	"Argentina",
	ARM:	"Armenia",
	ATG:	"Antigua y Barbuda",
	AUS:	"Australia",
	AUT:	"Austria ",
	AZE:	"Azerbaiyán",
	BDI:	"Burundi",
	BEL:	"Bélgica",
	BEN:	"Benín",
	BFA:	"Burkina Faso",
	BGD:	"Bangladesh",
	BGR:	"Bulgaria ",
	BHR:	"Bahréin",
	BHS:	"Bahamas ",
	BIH:	"Bosnia y Herzegovina",
	BLR:	"Bielorrusia",
	BLZ:	"Belice ",
	BOL:	"Bolivia",
	BRA:	"Brasil",
	BRB:	"Barbados ",
	BRN:	"Brunei-Darussalam ",
	BTN:	"Bután",
	BWA:	"Botsuana",
	CAF:	"República Centroafricana",
	CAN:	"Canadá ",
	CHE:	"Suiza ",
	CHL:	"Chile ",
	CHN:	"China",
	CIV:	"Costa de Marfil",
	CMR:	"Camerún",
	COD:	"República Democrática Popular del Congo",
	COG:	"República Democrática del Congo",
	COL:	"Colombia",
	COM:	"Comora",
	CPV:	"Cabo Verde",
	CRI:	"Costa Rica ",
	CUB:	"Cuba",
	CYP:	"Chipre ",
	CZE:	"República Checa ",
	DEU:	"Alemania ",
	DJI:	"Djibouti",
	DMA:	"Dominica",
	DNK:	"Dinamarca ",
	DOM:	"República Dominicana",
	DZA:	"Argelia",
	ECU:	"Ecuador",
	EGY:	"Egipto",
	ERI:	"Eritrea",
	ESP:	"España",
	EST:	"Estonia ",
	ETH:	"Etiopía",
	FIN:	"Finlandia ",
	FJI:	"Fiyi",
	FRA:	"Francia  ",
	FSM:	"Micronesia",
	GAB:	"Gabón",
	GBR:	"Reino Unido de Gran Bretaña e Irlanda del Norte",
	GEO:	"Georgia",
	GHA:	"Ghana",
	GIN:	"Guinea",
	GMB:	"Gambia",
	GNB:	"Guinea Bissau",
	GNQ:	"Guinea Ecuatorial",
	GRC:	"Grecia ",
	GRD:	"Granada",
	GRL:  "Groelandia",
	GTM:	"Guatemala",
	GUF:  "Guayana Francesa",
	GUM:	"Guam",
	GUY:	"Guyana",
	HND:	"Honduras",
	HRV:	"Croacia ",
	HTI:	"Haití",
	HUN:	"Hungría ",
	IDN:	"Indonesia",
	IND:	"India",
	IRL:	"Irlanda ",
	IRN:	"Irán",
	IRQ:	"Irak",
	ISL:	"Islandia ",
	ISR:	"Israel",
	ITA:	"Italia ",
	JAM:	"Jamaica",
	JOR:	"Jordania",
	JPN:	"Japón ",
	KAZ:	"Kazajstán",
	KEN:	"Kenia",
	KGZ:	"Kirguistán",
	KHM:	"Camboya",
	KIR:	"Kiribati",
	KNA:	"San Cristóbal y Nieves ",
	KOR:	"República de Corea (Corea del Sur)",
	KWT:	"Kuwait ",
	LAO:	"Laos",
	LBN:	"Líbano",
	LBR:	"Liberia",
	LBY:	"Libia",
	LCA:	"Santa Lucia ",
	LIE:	"Liechtenstein ",
	LKA:	"Sri Lanka",
	LSO:	"Lesoto",
	LTU:	"Lituania ",
	LUX:	"Luxemburgo ",
	LVA:	"Letonia",
	MAR:	"Marruecos",
	MCO:	"Mónaco ",
	MDA:	"Moldova",
	MDG:	"Madagascar ",
	MDV:	"Maldivas",
	MEX:	"México",
	MHL:	"Islas Marshall ",
	MKD:	"Macedonia ",
	MLI:	"Mali",
	MLT:	"Malta",
	MMR:	"Myanmar",
	MNE:	"Montenegro",
	MNG:	"Mongolia",
	MOZ:	"Mozambique",
	MRT:	"Mauritania",
	MUS:	"Mauricio",
	MWI:	"Malawi",
	MYS:	"Malasia ",
	NAM:	"Namibia",
	NCL:  "Nueva Caledonia",
	NER:	"Níger",
	NGA:	"Nigeria",
	NIC:	"Nicaragua",
	NLD:	"Reino de los Países Bajos (Holanda)",
	NOR:	"Noruege",
	NPL:	"Nepal",
	NRU:	"Nauru",
	NZL:	"Nueva Zelanda ",
	OMN:	"Omán",
	PAK:	"Pakistán",
	PAN:	"Panamá ",
	PER:	"Perú",
	PHL:	"Filipinas",
	PLW:	"Palaos",
	PNG:	"Papúa Nueva Guinea",
	POL:	"Polonia ",
	PRK:	"República Popular Democrática de Corea (Corea del Norte)",
	PRT:	"Portugal ",
	PRY:	"Paraguay ",
	PSE:	"Palestina",
	QAT:	"Qatar ",
	ROU:	"Rumania ",
	RUS:	"Rusia",
	RWA:	"Ruanda",
	SAU:	"Arabia Saudita",
	SDN:	"Sudán",
	SSD: 	"Sudán del Sur",
	SEN:	"Senegal",
	SGP:	"Singapur ",
	SLB:	"Islas Salomón ",
	SLE:	"Sierra Leona",
	SLV:	"El Salvador",
	SMR:	"San Marino ",
	SOL:  "Somalilandia",
	SOM:	"Somalia",
	SRB:	"Serbia",
	STP:	"Santo Tomé y Príncipe",
	SUR:	"Surinam",
	SVK:	"Eslovaquia ",
	SVN:	"Eslovenia ",
	SWE:	"Suecia",
	SWZ:	"Suazilandia",
	SYC:	"Seychelles",
	SYR:	"Siria",
	TCD:	"Chad",
	TGO:	"Togo",
	THA:	"Tailandia",
	TJK:	"Tayikistán",
	TKM:	"Turkmenistán",
	TLS:	"Timor Oriental",
	TON:	"Tonga",
	TTO:	"Trinidad y Tobago",
	TUN:	" Túnez",
	TUR:	"Turquía ",
	TUV:	"Tuvalu ",
	TWN:	"Taiwán",
	TZA:	"Tanzania",
	UGA:	"Uganda",
	UKR:	"Ucrania ",
	URY:	"Uruguay ",
	USA:	"Estados Unidos de América",
	UZB:	"Uzbekistán",
	VAT:	"Santa Sede (Ciudad del Vaticano) ",
	VCT:	"San Vicente y Granadinas ",
	VEN:	"Venezuela ",
	VNM:	"Vietnam",
	VUT:	"Vanuatu ",
	WSM:	"Samoa",
	YEM:	"Yemen",
	ZAF:	"Sudáfrica ",
	ZMB:	"Zambia",
	ZWE:	"Zimbabue"
}
